### ISSUE TITLE
type-check fails during build

### ISSUE THREAD

**Issue by akins-dev** [w3cj/stoker#12]
`Argument of type 'T' is not assignable to parameter of type 'ZodTypeAny'.
`
Got this error for `one-of`, `json-content-one-of` and `create-schema-error` while trying to build my app

**Comment by akins-dev** [comment]
I was able to fix it by replacing `ZodSchema` with `ZodTypeAny` imported directly from `zod`

```
import {
    OpenApiGeneratorV3,
    OpenAPIRegistry,
} from "@asteasolutions/zod-to-openapi";

import type { ZodTypeAny } from "zod";

const oneOf = <
    T extends ZodTypeAny,
>(schemas: T[]) => {
    const registry = new OpenAPIRegistry();

    schemas.forEach((schema, index) => {
        registry.register(index.toString(), schema);
    });

    const generator = new OpenApiGeneratorV3(registry.definitions);
    const components = generator.generateComponents();

    return components.components?.schemas ? Object.values(components.components!.schemas!) : [];
};
 
```

**Comment by w3cj** [comment]
Can you show an example of how you are using the functions?

**Comment by akins-dev** [comment]
> Can you show an example of how you are using the functions?

![image](https://github.com/user-attachments/assets/da45cc36-93c8-4c1d-87de-372793373a32)
![image](https://github.com/user-attachments/assets/b04292ea-a42a-4494-bfad-6f3545d228b7)
