### ISSUE TITLE
feat: add custom response object in not-found and on-error middlewares

### ISSUE THREAD

**Issue by pietrodev07** [w3cj/stoker#5]
Hi @w3cj, I would like to add to pass a custom response object for the **_not-found_** and _**on-error**_ middlewares.

What do you say? I can start a pr, thanks!

**Comment by w3cj** [comment]
That sounds good. I don't want to break the existing ones, so we might need new helpers like createNotFound and createOnError

**Comment by pietrodev07** [comment]
> That sounds good. I don't want to break the existing ones, so we might need new helpers like createNotFound and createOnError

Yes, another way is that the parameter is optional and we don't break anything! Tell me if you appreciate this approach!

**Comment by w3cj** [comment]
You can give it a try, but the current signature / examples do not invoke the methods, they are just passed in directly:

```ts
app.notFound(notFound);
app.onError(onError);
```

Needing to update to this would break existing usage:

```ts
app.notFound(notFound());
app.onError(onError());
```

If you can implement it with keeping the first signature that would be ideal.

If not we could possibly create a submodule called "stoker/middlewares/custom", so they can be imported with the same name, just different usage.

e.g.
```ts
import notFound from "stoker/middlewares/custom/not-found"

app.notFound(notFound(c => ({
  message: "use c here to customize message and use other context properties"
})));
```

**Comment by pietrodev07** [comment]
> You can give it a try, but the current signature / examples do not invoke the methods, they are just passed in directly:
> 
> ```ts
> app.notFound(notFound);
> app.onError(onError);
> ```
> 
> Needing to update to this would break existing usage:
> 
> ```ts
> app.notFound(notFound());
> app.onError(onError());
> ```
> 
> If you can implement it with keeping the first signature that would be ideal.
> 
> If not we could possibly create a submodule called "stoker/middlewares/custom", so they can be imported with the same name, just different usage.
> 
> e.g.
> 
> ```ts
> import notFound from "stoker/middlewares/custom/not-found"
> 
> app.notFound(notFound(c => ({
>   message: "use c here to customize message and use other context properties"
> })));
> ```

We can do something like this:

```typescript
const notFound = (c: Context, obj?: object) => {
  if (obj) return c.json(obj, NOT_FOUND);
  return c.json({ message: "default message" }, NOT_FOUND);
};

// with the default obj
app.notFound(notFound);

// with the custom obj
app.notFound((c) =>
  notFound(c, {
    message: "Custom not found",
    success: false,
  }),
);
```

**Comment by pietrodev07** [comment]
> 🤔 The more I think about it, for this use case, it might just make sense to pass in your own custom not found handler directly to hono instead of using this helper. The only benefit of the helper at that point is using `c.json` and setting the status code.
> 
> e.g. this seems simpler:
> 
> ```ts
> app.notFound((c) => c.json({
>   message: "Custom not found",
>   success: false,
> }, NOT_FOUND));
> ```
> 
> than trying to use the helper:
> 
> ```ts
> app.notFound((c) =>
>   notFound(c, {
>     message: "Custom not found",
>     success: false,
>   }),
> );
> ```

Yeah, in effect is very indifferent! But in my opinion, it's a cool small but very small feature!

Yeah, maybe it's not necessary!
