### ISSUE TITLE
fix: openapi cjs import

### ISSUE THREAD

**Issue by pietrodev07** [w3cj/stoker#6]
Hi, stoker now has problems with internal imports, can you fix it please? Thanks!

![image](https://github.com/user-attachments/assets/98d018b3-fe6d-4ed8-9a35-51d62cfd22fc)

**Comment by w3cj** [comment]
Can you share your tsconfig.json? I cannot replicate this issue.

**Comment by pietrodev07** [comment]
> Can you share your tsconfig.json? I cannot replicate this issue.

Yeah, it's the same of your hono-starter!

**Comment by w3cj** [comment]
I cloned the repo fresh, used jsonContentOneOf and do not see the error.

Do you have moduleResolution set to bundler in tsconfig: https://github.com/w3cj/hono-open-api-starter/blob/main/tsconfig.json#L8

Do you have type set to module in package.json: https://github.com/w3cj/hono-open-api-starter/blob/main/package.json#L3

How are you importing jsonContentOneOf

**Comment by pietrodev07** [comment]
I also cloned it this morning, but it gave an error!!

Sorry which version of nodejs are you using?

**Comment by w3cj** [comment]
Tested with v20.18.0 and v22.10.0

**Comment by pietrodev07** [comment]
> Tested with v20.18.0 and v22.10.0

Can you try with my version? 20.14.0

it seems very stranger thing....

**Comment by w3cj** [comment]
Tried with 20.14.0 and no issue.

**Comment by pietrodev07** [comment]
> Tried with 20.14.0 and no issue.

I get an error cloning your starter repo, I don't know to say! 🤣

**Comment by w3cj** [comment]
Are you on windows / mac or linux? I am testing on a mac.

**Comment by pietrodev07** [comment]
> Are you on windows / mac or linux? I am testing on a mac.

I'm on windows but I use git bash with zsh, so bash linux friendly!

**Comment by pietrodev07** [comment]
> > Are you on windows / mac or linux? I am testing on a mac.
> 
> I'm on windows but I use git bash with zsh, so bash linux friendly!
> 

I downgraded to pnpm 8.15.4 version and now everything works, with 9.9.0 version gives an error.

Which version of pnpm are you using?
